package com.bluesoft.entities;
// Generated 29-Mar-2016 02:15:21 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * System generated by hbm2java
 */
public class System implements java.io.Serializable {

	private long id;
	private String description;
	private String name;
	private String supporGroup;
	private Set systemContracts = new HashSet(0);

	public System() {
	}

	public System(long id) {
		this.id = id;
	}

	public System(long id, String description, String name, String supporGroup, Set systemContracts) {
		this.id = id;
		this.description = description;
		this.name = name;
		this.supporGroup = supporGroup;
		this.systemContracts = systemContracts;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSupporGroup() {
		return this.supporGroup;
	}

	public void setSupporGroup(String supporGroup) {
		this.supporGroup = supporGroup;
	}

	public Set getSystemContracts() {
		return this.systemContracts;
	}

	public void setSystemContracts(Set systemContracts) {
		this.systemContracts = systemContracts;
	}

}
